routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');





Route::group(['middleware' => ['auth'], 'prefix' => 'admin'], function()
{
	Route::resource('offers', 'OfferController');

	Route::resource('offerResponses', 'OfferResponseController');

	Route::resource('orders', 'OrderController');

	Route::resource('categories', 'CategoryController');

	Route::resource('pages', 'PageController');

	Route::resource('products', 'ProductController');


});

Route::group(['namespace' => 'Client', 'as' => 'client.'], function()
{

  	Route::get('dang-ky', 'Auth\RegisterController@showRegistrationForm')->name('register');
  	Route::post('dang-ky', 'Auth\RegisterController@register')->name('register.submit');

	Route::get('dang-nhap', 'Auth\LoginController@showLoginForm')->name('login');
 	Route::post('dang-nhap', 'Auth\LoginController@login')->name('login.post');

 	Route::post('/dang-xuat' , 'Auth\LoginController@logout')->name('logout');

 	Route::get('dashboard', 'DashboardController@index')->name('dashboard');

 	

	Route::get('sell/product/{product}', 'ProductController@sell')->name('product.sell');
	Route::post('follow/product/{product}', 'ProductController@follow')->name('product.follow');

	Route::get('follow/products', 'ProductController@followList')->name('follow.products');

	
	Route::get('response/offer/create/{offer}', 'OfferResponseController@create')->name('response.offer.create');
	Route::post('response/offer/store', 'OfferResponseController@store')->name('response.offer.store');
	Route::get('responses/offer/{offerId}', 'OfferResponseController@index')->name('response.offer.index');


	Route::get('buy/offer/list', 'BuyController@offer')->name('buy.offer.index');
	Route::get('buy/offer/create', 'OfferController@create')->name('offer.create');
	Route::post('buy/offer/store', 'OfferController@store')->name('offer.store');
	
	Route::get('buy/responses/{offerId}', 'BuyController@responses')->name('buy.response.index');
	Route::get('buy/follow/products', 'BuyController@followList')->name('buy.follow.products');

	Route::get('buy/order/list', 'BuyController@listOrder')->name('buy.order.list');
	Route::get('buy/order/create/{response}', 'BuyController@createOrder')->name('buy.order.create');
	Route::post('buy/order/store', 'BuyController@storeOrder')->name('buy.order.store');
	Route::get('user/edit', 'UserController@edit')->name('user.edit');
	Route::post('user/update', 'UserController@update')->name('user.update');
	Route::get('them-ma-moi', 'ProductController@create')->name('product.create');
	Route::post('them-ma-moi', 'ProductController@store')->name('product.store');

	Route::get('sell/products', 'SellController@sellList')->name('sell.products');
	Route::get('sell/response', 'SellController@response')->name('sell.response');
	Route::get('sell/request', 'SellController@request')->name('sell.request');
	Route::get('sell/answer/{offer}', 'SellController@createAnswer')->name('sell.answer.create');
	Route::post('sell/answer/store', 'SellController@storeAnswer')->name('sell.answer.store');

	Route::get('sell/product/price/edit/{product}', 'SellController@editPrice')->name('sell.price.edit');
	Route::post('sell/product/price/update/{product}', 'SellController@updatePrice')->name('sell.price.update');
});

 	Route::get('/', 'Front\HomeController@index')->name('home');
 	Route::get('product/{product}', 'Front\HomeController@detail')->name('product.detail');
 	Route::get('san-pham', 'Front\HomeController@products')->name('product.list');
 	Route::get('tim-kiem', 'Front\HomeController@productSearch')->name('product.search');

 	Route::get('profile/{user}', 'Front\ProfileController@index')->name('profile');

app/Http/Controllers/Client/BuyController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\CreateOfferRequest;
use App\Http\Requests\UpdateOfferRequest;
use App\Http\Requests\CreateOrderRequest;

use App\Repositories\OfferRepository;
use App\Repositories\OrderRepository;

use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Models\Offer;
use App\Models\OfferResponse;
use App\Models\Order;
//use App\Models\City;

class BuyController extends AppBaseController
{
    /** @var  OfferRepository */
    private $offerRepository;
    private $orderRepository;



    public function __construct(OfferRepository $offerRepo,OrderRepository $orderRepo)
    {
        $this->offerRepository = $offerRepo;
        $this->orderRepository = $orderRepo;
    }

    
    public function responses(Request $request , $offerId)
    {

       $responses =  \DB::table('offer_responses as off')
        ->select('u.name as seller_name','off.id','off.price' ,'off.quantity as sell_quantity','o.price as customer_price', 'o.quantity' ,'p.name as product_name','off.created_at as responses_time','o.created_at as request_time')
        ->join('offers as o','off.request_id', '=', 'o.id')
        ->join('sellers as s','off.seller_id', '=', 's.id')
        ->join('users as u','u.seller_id', '=', 's.id')
        ->join('products as p','o.product_id', '=', 'p.id')
       // ->where('o.customer_id',2)
        ->where('o.id',$offerId)
        ->get();
       // dd($responses);
        return view('front.client.buy.responses')
            ->with('responses', $responses);
    }

    public function listOrder(Request $request ){
        $orders =  Order::with(['seller','product'])->where('customer_id', \Auth()->user()->customer_id )->paginate(10);

        return view('front.client.buy.order.list')
            ->with('orders', $orders);
    }


    public function createOrder(Request $request ,OfferResponse $response){
        //$cities = City::pluck('name','id')->toArray();,compact('cities')
        return view('front.client.buy.order.create')
            ->with('response', $response);
    }

    public function storeOrder(CreateOrderRequest $request)
    {
        $input = $request->all();

        $order = $this->orderRepository->create($input);

        Flash::success('Order saved successfully.');

        return redirect(route('orders.index'));
    }

      public function offer(Request $request)
    {
        //$sells = \Auth()->user()->seller->products->pluck('id')->toArray();
        //Offer
        $offers = Offer::where('customer_id', \Auth()->user()->customer_id)->paginate(10) ;// $this->offerRepository->paginate(10);
      //  dd($offers);

        return view('front.client.offers_request')
            ->with('offers', $offers);
    }

     public function followList(Request $request)
    {
        $customer = \Auth()->user()->customer;
        $products = $customer->products;
        return view('front.client.follows',compact('products'));

    }

    
}

app/Http/Controllers/Client/DashboardController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Order;
use DB;
class DashboardController extends Controller
{

    public function index()
    {
    	$user = \Auth()->user();
    	//echo $user->seller->id;die;
    	$totalSell = Order::where('seller_id',$user->seller->id )->count();
    	$totalBuy = Order::where('customer_id',$user->customer->id )->count();
    	$sell = DB::table("orders")->selectRaw('orders.price*orders.quantity as total')->where('seller_id',$user->seller->id )->first();
    	$amountSell= isset($sell->total) ? $sell->total : 0;
    	//dd($amountSell->total);

        return view('front.client.dashboard',compact('totalSell','totalBuy','amountSell'));
    }
    public function __construct()
    {
    }
}

app/Http/Controllers/Client/OfferController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\CreateOfferRequest;
use App\Http\Requests\UpdateOfferRequest;
use App\Repositories\OfferRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Models\Offer;
use App\Models\Product;

class OfferController extends AppBaseController
{
    /** @var  OfferRepository */
    private $offerRepository;

    public function __construct(OfferRepository $offerRepo)
    {
        $this->offerRepository = $offerRepo;
    }

    /**
     * Display a listing of the Offer.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $sells = \Auth()->user()->seller->products->pluck('id')->toArray();
        //Offer
        $offers = Offer::whereIn('product_id',$sells)->paginate(10) ;// $this->offerRepository->paginate(10);
      //  dd($offers);

        return view('front.client.offers_request')
            ->with('offers', $offers);
    }

    /**
     * Show the form for creating a new Offer.
     *
     * @return Response
     */
    public function create()
    {
        return view('front.client.create_offer');
    }

    /**
     * Store a newly created Offer in storage.
     *
     * @param CreateOfferRequest $request
     *
     * @return Response
     */
    public function store(CreateOfferRequest $request)
    {
        $request->request->add(['customer_id' => \Auth()->user()->customer_id,'status' => 1]);
        $input = $request->all();
        $request->request->add(['variable' => 'value']); //add request

         //send offer to all realtive seller 
        $sellers= $this->getSellers($input['product_id']);

        $offer = $this->offerRepository->create($input);
        $offer->sellers()->attach($sellers);
        Flash::success('Offer saved successfully.');

        return redirect(route('offers.index'));
    }

     public function getSellers($productId){
         $product = Product::find($productId );
         $sellers= $product->sellers->pluck('id')->toArray();
          return  $sellers;
     }
    /**
     * Display the specified Offer.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $offer = $this->offerRepository->find($id);

        if (empty($offer)) {
            Flash::error('Offer not found');

            return redirect(route('offers.index'));
        }

        return view('offers.show')->with('offer', $offer);
    }

    /**
     * Show the form for editing the specified Offer.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $offer = $this->offerRepository->find($id);

        if (empty($offer)) {
            Flash::error('Offer not found');

            return redirect(route('offers.index'));
        }

        return view('offers.edit')->with('offer', $offer);
    }

    /**
     * Update the specified Offer in storage.
     *
     * @param int $id
     * @param UpdateOfferRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOfferRequest $request)
    {
        $offer = $this->offerRepository->find($id);

        if (empty($offer)) {
            Flash::error('Offer not found');

            return redirect(route('offers.index'));
        }

        $offer = $this->offerRepository->update($request->all(), $id);

        Flash::success('Offer updated successfully.');

        return redirect(route('offers.index'));
    }

    /**
     * Remove the specified Offer from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $offer = $this->offerRepository->find($id);

        if (empty($offer)) {
            Flash::error('Offer not found');

            return redirect(route('offers.index'));
        }

        $this->offerRepository->delete($id);

        Flash::success('Offer deleted successfully.');

        return redirect(route('offers.index'));
    }

    public function responses(Request $request , $offerId)
    {

       $responses =  \DB::table('offer_responses as off')
        ->select('u.name as seller_name','off.price' ,'o.price as customer_price', 'o.quantity' ,'p.name as product_name','off.created_at as responses_time','o.created_at as request_time')
        ->join('offers as o','off.request_id', '=', 'o.id')
        ->join('sellers as s','off.seller_id', '=', 's.id')
        ->join('users as u','u.seller_id', '=', 's.id')
        ->join('products as p','o.product_id', '=', 'p.id')
        ->where('o.customer_id',2)
        ->where('o.id',$offerId)
        ->get();
       // dd($responses);
        return view('front.client.buy.responses')
            ->with('responses', $responses);
    }

}

app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\CreateProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Repositories\ProductRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Models\Product;
use App\Models\Category;

class ProductController extends AppBaseController
{
    /** @var  ProductRepository */
    private $productRepository;

    public function __construct(ProductRepository $productRepo)
    {
        $this->productRepository = $productRepo;
    }

    /**
     * Display a listing of the Product.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $products = $this->productRepository->paginate(10);


        return view('products.index')
            ->with('products', $products);
    }

     public function create()
    {
        $categories = Category::pluck('name','id')->toArray();
        return view('front.client.products.create',compact('categories'));
    }

    /**
     * Store a newly created Product in storage.
     *
     * @param CreateProductRequest $request
     *
     * @return Response
     */
    public function store(CreateProductRequest $request)
    {
        $request->request->add(['user_id' => \Auth()->user()->id,'status' => 0]);
        $input = $request->all();
        $product = $this->productRepository->create($input);

        Flash::success('Product saved successfully.');

        return redirect(route('home'));
    }

    public function sell(Product $product)
    {
        $user = \Auth()->user();
        $product->sellers()->sync($user->id);
        return view('front.product.price_create');
    }

    public function follow(Product $product)
    {
        
        $user = \Auth()->user();
        $product->customers()->attach($user->id);

         return response()->json([
            'status' => 'success',
           'message' => 'theo dõi thành công',
        ]);
    }
    public function followList(Product $product)
    {
        
        $customer = \Auth()->user()->customer;
        $products = $customer->products;
        return view('front.client.follows',compact('products'));

    }

    public function sellList(Product $product)
    {
        
        $seller = \Auth()->user()->seller;
        $products = $seller->products;
        return view('front.client.sells',compact('products'));

    }
}

app/Http/Controllers/Client/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\User;

class ProfileController extends AppBaseController
{
  
    public function __construct()
    {
    }

    
    public function index(Request $request , User $user )
    {
        return view('front.client.profile',compact('user'));
    }
}

app/Http/Controllers/Client/UserController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\User;
use App\Models\City;

class UserController extends AppBaseController
{
  
    public function __construct()
    {
    }

    
    public function edit(Request $request )
    {
    	$user = \Auth()->user();
        $cities = City::pluck('name','id')->toArray();
        return view('front.client.user',compact('user','cities'));
    }

    public function update(Request $request )
    {
        $input = $request->all();
        $user = \Auth()->user();
         $user->update($input);
       /* $order = $this->orderRepository->create($input);*/
       if ($request->hasFile('thumbnail'))
            $user->saveImage($request->file('thumbnail'));


        Flash::success('Profile saved successfully.');

        return redirect(route('client.user.edit'));
    }
}

resources/views/front/client/sell/answer_form.blade.php
		  <div class="job-box">
		   <div class="job-header">
		    <h4>Tạo đơn chào hàng</h4>
		   </div>
		 {!! Form::open(['route' => 'client.sell.answer.store','id'=>'addform']) !!}
		  {!! Form::hidden('request_id',old('request_id',$offer->id)) !!}
		 {!! Form::hidden('customer_id',old('customer_id',$offer->customer_id)) !!}

              <div class="form-group">	
			    <label>Giá bán</label>
                <input type="text" name="price" class="form-control" placeholder="Giá" value="">
              </div>   

              <div class="form-group">	
			    <label>Số lượng </label>
                <input type="number" name="quantity" class="form-control" placeholder="Số lượng" value="">
              </div>  

			  <div class="form-group">	
			   <label>Mô tả</label>
			   <textarea name="description" class="form-control" rows="5" placeholder=""></textarea>
			  </div> 
			  
              <button class="kafe-btn kafe-btn-mint-small full-width" type="button" onclick="save()">Submit</button>
           {!! Form::close() !!}
          </div><!-- /.job-box -->		
		

resources/views/front/client/sell/offers.blade.php
@extends('front.layout.dashboard')

@section('content')
  <div class="col-sm-8 col-md-9">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Đơn hỏi hàng </h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                 <div class="table-responsive">
                  <table id="example1" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>Người mua</th>
                        <th>Sản phẩm</th>
                        <th>Số lượng</th>
                        <th>Giá kì vọng</th>
                        <th>Thời gian tạo</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($offers as $offer)
                      <tr>
                        <td>{{$offer->customer->user->name}}</td>
                        <td>{{$offer->product->name}}</td>
                        <td>{{$offer->quantity}}</td>
                        <td>{{$offer->price}}</td>
                        <td>{{$offer->created_at}}</td>
                        <td>
                           <a onclick="answer('{{route('client.sell.answer.create',$offer->id)}}')" href="#" class="btn btn-success btn-xs" data-toggle="tooltip" title="Gửi chào hàng"><span class="fa fa-eye"></span></a>
                          
                           </tr>
                      @endforeach
                    </tbody>
                  
                  </table>
                 </div><!-- /.table-responsive -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->        
      
    
    
      </div><!-- /.col-md-9 --> 
         

 <!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <!-- <h5 class="modal-title" id="exampleModalLongTitle">Danh sách đơn chào hàng</h5> -->
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modalContent">
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>        
@endsection


@section('js')
<script type="text/javascript">
function answer(url){
  $.ajax({
            url: url ,
            type: 'GET',
            data: {
               //"code": code,
            },
            success: function (html) {
                $("#modalContent").html(html);
                $("#modal").modal('show');

            },
            error: function (xhr) {
               
            }
        });
}

function save(){
        url=$('#addform').attr('action');
        var formData = new FormData($('#addform')[0]);    
           $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: "JSON",
                    data: formData,
                    cache:false,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.status === "success") {
                            toastr.success(response.message);
                            $("#modal").modal('hide');
                        } else {
                           toastr.error('error!');
                        }

                    },
                    error: function (xhr) {
                    }
                });
    }

</script>
@endsection

resources/views/front/client/sell/price_form.blade.php
		  <div class="job-box">
		   <div class="job-header">
		    <h4>Cập nhật giá</h4>
		   </div>
		 {!! Form::open(['route' => ['client.sell.price.update',$product->id ],'id'=>'editform']) !!}
              <div class="form-group">	
			    <label>Giá bán</label>
                <input type="text" name="price" class="form-control" placeholder="Giá" value="{{old('price',request()->input('price'))}}">
              </div>   

			
              <button class="kafe-btn kafe-btn-mint-small full-width" type="button" onclick="save()">Submit</button>
           {!! Form::close() !!}
          </div><!-- /.job-box -->		
		

resources/views/front/client/sell/products.blade.php
@extends('front.layout.dashboard')

@section('content')
  <div class="col-sm-8 col-md-9">
      
      <div class="pro-nav text-center">
           <ul class="nav pro-nav-tabs nav-tabs-dashed">
            <li><a href="workroom.html">Overview & Discussions</a></li>
            <li><a href="milestone.html">Milestones</a></li>
            <li class="active"><a href="task.html">Tasks</a></li>
            <li><a href="timesheet.html">Timesheets</a></li>
            <li><a href="file.html">Files</a></li>
            <li><a href="link.html">Links</a></li>
            <li><a href="bug.html">Bugs</a></li>
            <li><a href="payment.html">Payments</a></li>
            <li><a href="rate.html">Rate the Freelancer</a></li>
              
           </ul>  
          </div><!-- /.pro-nav -->

      <div class="button-box">
       <a href="#addm" class="kafe-btn kafe-btn-mint-small" data-toggle="modal">Add Task</a>
          </div><!-- /.prop-info -->      

      
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Sản phẩm đang bán </h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                 <div class="table-responsive">
                  <table id="example1" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Milestone</th>
                        <th>Date to start</th>
                        <th>Date to end</th>
                        <th>Progress</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($products as $product)
                      <tr>
                        <td>{{$product->name}}</td>
                        <td>{{$product->pivot->price}}</td>
                        <td>{{$product->created_at}}</td>
                        <td>31th July 2018</td>
              <td>
                        <div class="progress-xxs not-rounded mb-0 inline-block progress" style="width: 100%; margin-right: 5px">
                          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%;" data-toggle="tooltip" title="30%"></div>
                        </div>
                        </td>
                        <td>
           
                          <a onclick="answer('{{route('client.sell.price.edit',$product->id)}}' ,{{$product->pivot->price}})" href="#" class="btn btn-success btn-xs" data-toggle="tooltip" title="Gửi chào hàng"><span class="fa fa-edit"></span></a>
                      </tr>
                      @endforeach
                    </tbody>
                   <!--  <tfoot>
                      <tr>
                        <th>Name</th>
                        <th>Milestone</th>
                        <th>Date to start</th>
                        <th>Date to end</th>
                        <th>Progress</th>
                        <th>Action</th>
                      </tr>
                    </tfoot> -->
                  </table>
                 </div><!-- /.table-responsive -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->        
      
    
    
      </div><!-- /.col-md-9 --> 
         


 <!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <!-- <h5 class="modal-title" id="exampleModalLongTitle">Danh sách đơn chào hàng</h5> -->
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modalContent">
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>     

@endsection



@section('js')
<script type="text/javascript">
function answer(url , price){
  $.ajax({
            url: url ,
            type: 'GET',
            data: {
               "price": price,
            },
            success: function (html) {
                $("#modalContent").html(html);
                $("#modal").modal('show');

            },
            error: function (xhr) {
               
            }
        });
}

function save(){
        url=$('#editform').attr('action');
        var formData = new FormData($('#editform')[0]);    
           $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: "JSON",
                    data: formData,
                    cache:false,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.status === "success") {
                            toastr.success(response.message);
                            $("#modal").modal('hide');
                        } else {
                           toastr.error('error!');
                        }

                    },
                    error: function (xhr) {
                    }
                });
    }

</script>
@endsection

resources/views/front/client/sell/response.blade.php
@extends('front.layout.dashboard')

@section('content')
  <div class="col-sm-8 col-md-9">
      
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Danh sách đơn chào hàng </h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                 <div class="table-responsive">
                  <table id="example1" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>Sản phẩm</th>
                        <th>Giá kì vọng</th>
                        <th>Số lượng hỏi mua</th>
                        <th>Thời gian hỏi hàng</th>
                        <th>Người mua</th>
                        <th>Giá bán</th>
                         <th>Số lượng bán</th>
                         <th>Thời gian trả lời</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($responses as $response)
                      <tr>
                        <td>{{$response->product_name}}</td>
                        <td>{{$response->customer_price}}</td>
                        <td>{{$response->quantity}}</td>
                        <td>{{$response->request_time}}</td>
                         <td>{{$response->buyer_name}}</td>
                        <td>{{$response->price}}</td>
                        <td>{{$response->sell_quantity}}</td>
                        <td>{{$response->responses_time}}</td>
                        <td>
                            <!-- <a href="#" class="btn btn-success btn-xs" data-toggle="tooltip" title="Edit"><span class="fa fa-edit"></span></a></td>
                             -->                      
                           </tr>
                      @endforeach
                    </tbody>
                   
                  </table>
                 </div><!-- /.table-responsive -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->  
   </div>                  
@endsection