routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');





Route::group(['middleware' => ['auth'], 'prefix' => 'admin'], function()
{
	Route::resource('offers', 'OfferController');

	Route::resource('offerResponses', 'OfferResponseController');

	Route::resource('orders', 'OrderController');

	Route::resource('categories', 'CategoryController');

	Route::resource('pages', 'PageController');

	Route::resource('products', 'ProductController');


});

Route::group(['namespace' => 'Client', 'as' => 'client.'], function()
{

  	Route::get('dang-ky', 'Auth\RegisterController@showRegistrationForm')->name('register');
  	Route::post('dang-ky', 'Auth\RegisterController@register')->name('register.submit');

	Route::get('dang-nhap', 'Auth\LoginController@showLoginForm')->name('login');
 	Route::post('dang-nhap', 'Auth\LoginController@login')->name('login.post');

 	Route::post('/dang-xuat' , 'Auth\LoginController@logout')->name('logout');

 	Route::get('dashboard', 'DashboardController@index')->name('dashboard');

 	

	Route::get('sell/product/{product}', 'ProductController@sell')->name('product.sell');
	Route::post('follow/product/{product}', 'ProductController@follow')->name('product.follow');

	Route::get('follow/products', 'ProductController@followList')->name('follow.products');

	
	Route::get('response/offer/create/{offer}', 'OfferResponseController@create')->name('response.offer.create');
	Route::post('response/offer/store', 'OfferResponseController@store')->name('response.offer.store');
	Route::get('responses/offer/{offerId}', 'OfferResponseController@index')->name('response.offer.index');


	Route::get('buy/offer/list', 'BuyController@offer')->name('buy.offer.index');
	Route::get('buy/offer/create', 'OfferController@create')->name('offer.create');
	Route::post('buy/offer/store', 'OfferController@store')->name('offer.store');
	
	Route::get('buy/responses/{offerId}', 'BuyController@responses')->name('buy.response.index');
	Route::get('buy/follow/products', 'BuyController@followList')->name('buy.follow.products');

	Route::get('buy/order/list', 'BuyController@listOrder')->name('buy.order.list');
	Route::get('buy/order/create/{response}', 'BuyController@createOrder')->name('buy.order.create');
	Route::post('buy/order/store', 'BuyController@storeOrder')->name('buy.order.store');
	Route::get('user/edit', 'UserController@edit')->name('user.edit');
	Route::post('user/update', 'UserController@update')->name('user.update');
	Route::get('them-ma-moi', 'ProductController@create')->name('product.create');
	Route::post('them-ma-moi', 'ProductController@store')->name('product.store');

	Route::get('sell/products', 'SellController@sellList')->name('sell.products');
	Route::get('sell/response', 'SellController@response')->name('sell.response');
	Route::get('sell/request', 'SellController@request')->name('sell.request');
	Route::get('sell/answer/{offer}', 'SellController@createAnswer')->name('sell.answer.create');
	Route::post('sell/answer/store', 'SellController@storeAnswer')->name('sell.answer.store');

	Route::get('sell/product/price/edit/{product}', 'SellController@editPrice')->name('sell.price.edit');
	Route::post('sell/product/price/update/{product}', 'SellController@updatePrice')->name('sell.price.update');
});

 	Route::get('/', 'Front\HomeController@index')->name('home');
 	Route::get('product/{product}', 'Front\HomeController@detail')->name('product.detail');
 	Route::get('san-pham', 'Front\HomeController@products')->name('product.list');
 	Route::get('tim-kiem', 'Front\HomeController@productSearch')->name('product.search');

 	Route::get('profile/{user}', 'Front\ProfileController@index')->name('profile');

app/Models/Product.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use App\Common\Imageable;

/**
 * @SWG\Definition(
 *      definition="Product",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="rating",
 *          description="rating",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="code",
 *          description="code",
 *          type="string"
 *      )
 * )
 */
class Product extends Model implements HasMedia
{
    use SoftDeletes,HasMediaTrait,Imageable;

    public $table = 'products';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'id',
        'name',
        'description',
        'rating',
        'code',
        'category_id',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'rating' => 'integer',
        'code' => 'string',
        'status' => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

     /*public function categories()
    {
        return $this->belongsToMany(Category::class)->withTimestamps();
    }*/

    public function sellers()
    {
        return $this->belongsToMany(Seller::class)->withPivot('price');//->withTimestamps()
    }
    public function customers()
    {
        return $this->belongsToMany(Customer::class);//->withTimestamps()
    }
    public function category()
    {
        return $this->belongsTo(Category::class);//->withTimestamps()
    }
     public function getLargeThumb()
    {
        //return $this->thumbnail('images', 'large');
        if(null !== $this->getMedia('thumbnail')->last()){ 
            return $this->getMedia('thumbnail')->last()->getUrl('large');
        }else{
           return "https://via.placeholder.com/890x500";
        } 
    }
    
   public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('small')
             ->nonQueued()
             ->crop('crop-center', 45 , 45 );

        $this->addMediaConversion('medium')
            ->nonQueued()
             ->crop('crop-center', 480 , 270 );
/*
            ->width(320)
            ->height(180);*/
            
        $this->addMediaConversion('large')
             ->nonQueued()
             ->crop('crop-center', 890 , 500 );
           /* ->width(890)
            ->height(500);    */    
    }
}

app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\CreateProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Repositories\ProductRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Models\Product;
use App\Models\Category;

class ProductController extends AppBaseController
{
    /** @var  ProductRepository */
    private $productRepository;

    public function __construct(ProductRepository $productRepo)
    {
        $this->productRepository = $productRepo;
    }

    /**
     * Display a listing of the Product.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $products = $this->productRepository->paginate(10);


        return view('products.index')
            ->with('products', $products);
    }

     public function create()
    {
        $categories = Category::pluck('name','id')->toArray();
        return view('front.client.products.create',compact('categories'));
    }

    /**
     * Store a newly created Product in storage.
     *
     * @param CreateProductRequest $request
     *
     * @return Response
     */
    public function store(CreateProductRequest $request)
    {
        $request->request->add(['user_id' => \Auth()->user()->id,'status' => 0]);
        $input = $request->all();
        $product = $this->productRepository->create($input);

        Flash::success('Product saved successfully.');

        return redirect(route('home'));
    }

    public function sell(Product $product)
    {
        $user = \Auth()->user();
        $product->sellers()->sync($user->id);
        return view('front.product.price_create');
    }

    public function follow(Product $product)
    {
        
        $user = \Auth()->user();
        $product->customers()->attach($user->id);

         return response()->json([
            'status' => 'success',
           'message' => 'theo dõi thành công',
        ]);
    }
    public function followList(Product $product)
    {
        
        $customer = \Auth()->user()->customer;
        $products = $customer->products;
        return view('front.client.follows',compact('products'));

    }

    public function sellList(Product $product)
    {
        
        $seller = \Auth()->user()->seller;
        $products = $seller->products;
        return view('front.client.sells',compact('products'));

    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Repositories\ProductRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\Models\Product;
use App\Models\Category;

class ProductController extends AppBaseController
{
    /** @var  ProductRepository */
    private $productRepository;

    public function __construct(ProductRepository $productRepo)
    {
        $this->productRepository = $productRepo;
    }

    /**
     * Display a listing of the Product.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
       $categories = Category::pluck('name','id')->toArray();

        $products = $this->productRepository->paginate(10);

        return view('products.index',compact('categories'))
            ->with('products', $products);
    }

    /**
     * Show the form for creating a new Product.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Category::pluck('name','id')->toArray();
        return view('products.create',compact('categories'));
    }

    /**
     * Store a newly created Product in storage.
     *
     * @param CreateProductRequest $request
     *
     * @return Response
     */
    public function store(CreateProductRequest $request)
    {
        $input = $request->all();

        $product = $this->productRepository->create($input);

        Flash::success('Product saved successfully.');

        return redirect(route('products.index'));
    }

    /**
     * Display the specified Product.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $product = $this->productRepository->find($id);
        $sellers = $product->sellers->pluck('id')->toArray();
        $customers = $product->customers->pluck('id')->toArray();
        $userId = \Auth()->user()->id;
        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }

        return view('products.show',compact(['customers','sellers','userId']))->with('product', $product);
    }

    /**
     * Show the form for editing the specified Product.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
      $categories = Category::pluck('name','id')->toArray();

        $product = $this->productRepository->find($id);
      //  dd($product->getLargeThumb());

        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }

        return view('products.edit',compact('categories'))->with('product', $product);
    }

    /**
     * Update the specified Product in storage.
     *
     * @param int $id
     * @param UpdateProductRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProductRequest $request)
    {
        $product = $this->productRepository->find($id);
        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }

        $product = $this->productRepository->update($request->all(), $id);


        if ($request->hasFile('thumbnail'))
            $product->saveImage($request->file('thumbnail'));

        /*if ($request->hasFile('thumbnail')) {
            $product->addMedia($request->file('thumbnail'))->toMediaCollection('thumbnail', env('FILESYSTEM_DRIVER', 'local'));
        }*/

        Flash::success('Product updated successfully.');

        return redirect(route('products.index'));
    }

    /**
     * Remove the specified Product from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $product = $this->productRepository->find($id);

        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }

        $this->productRepository->delete($id);

        Flash::success('Product deleted successfully.');

        return redirect(route('products.index'));
    }
    public function sell(Product $product)
    {
        
        $user = \Auth()->user();
        $product->sellers()->sync($user->id);

        //dd($user->id);
        Flash::success('Product deleted successfully.');

        return redirect(route('products.show',$product->id));
    }

    public function follow(Product $product)
    {
        
        $user = \Auth()->user();
        $product->customers()->sync($user->id);

        //dd($user->id);
        Flash::success('Product deleted successfully.');

        return redirect(route('products.show',$product->id));
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('products.index') !!}">Product</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Product</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'products.store']) !!}

                                   @include('products.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/products/datatables_actions.blade.php
{!! Form::open(['route' => ['products.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('products.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('products.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('products.index') !!}">Product</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Product</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'patch','files'=>true]) !!}

                              @include('products.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/products/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Rating Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rating', 'Rating:') !!}
    {!! Form::text('rating', null, ['class' => 'form-control']) !!}
</div>

<!-- Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('code', 'Code:') !!}
    {!! Form::text('code', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('category_id', 'Category:') !!}
    {!! Form::select('category_id', $categories,null, ['class' => 'form-control']) !!}
</div>


<div class="form-group col-sm-6">
    {!! Form::label('status', 'Trạng thái:') !!}
    <label class="checkbox-inline">
     {!! Form::hidden('status', 0) !!}
    {!! Form::checkbox('status',1,null) !!}
     </label>
</div>

<input type="file" name="thumbnail">
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('products.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Products</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Products
                             <a class="pull-right" href="{{ route('products.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('products.table')
                              <div class="pull-right mr-3">
                                     
        @include('coreui-templates::common.paginate', ['records' => $products])

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/products/prices.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="products-table">
        <thead>
            <tr>
        <th>Name</th>
         <th>Price</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($product->sellers as $seller)
            <tr>
            <td>{{ $seller->name }}</td>
            <td>{{ $seller->pivot->price }}</td>
                <td>
                    <div class='btn-group'>
                        <a href="{{ route('offers.create', ['product_id'=>$product->id,'seller_id'=>$seller->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('products.index') }}">Product</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('products.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                <span class="badge badge-danger" >Đang có {{count($sellers)}} người bán
                                </span>
                                 <span class="badge badge-success" >
                                Đang có {{count($customers)}} người theo dõi
                                </span>
                                @if(!in_array($userId,$sellers))
                                <a> class="btn btn-block btn-danger" href="{{route('product.sell',$product->id)}}" >Sell this product</a>
                                @else
                                <span class="badge badge-success" >
                                Đang bán sp này
                                 </span>
                                @endif

                                 @if(!in_array($userId,$customers))
                                <a class="btn btn-block btn-danger" href="{{route('product.follow',$product->id)}}" >Follow this product</a>
                                @else
                                <span class="badge badge-success" >
                                Đã follow
                                </span>
                                 @endif


                                 @include('products.prices')
                                 @include('products.show_fields')
                                
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/products/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $product->id }}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $product->name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $product->description }}</p>
</div>

<!-- Rating Field -->
<div class="form-group">
    {!! Form::label('rating', 'Rating:') !!}
    <p>{{ $product->rating }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $product->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $product->updated_at }}</p>
</div>

<!-- Code Field -->
<div class="form-group">
    {!! Form::label('code', 'Code:') !!}
    <p>{{ $product->code }}</p>
</div>

resources/views/products/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="products-table">
        <thead>
            <tr>
                <th>Id</th>
        <th>Name</th>
        <th>Category</th>
        <th>Code</th>
        <th>Trạng thái</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
            <tr>
                <td>{{ $product->id }}</td>
            <td>{{ $product->name }}</td>
            <td>{{ $categories[$product->category_id]  }}</td>
            <td>{{ $product->code }}</td>
            <td>@if( $product->status) Duyệt @else Chờ duyệt @endif</td>
                <td>
                    {!! Form::open(['route' => ['products.destroy', $product->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('products.show', [$product->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('products.edit', [$product->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>